 # This is a basic workflow to help you get started with Actions

name: Publish package to Github

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

concurrency:
  group: ${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release-please:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2.3.4
     - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Generate .npmrc for Private Repo
        uses: TwiggyBuffalo/create-npmrc@master
        with:
          org_name: fullfacing
        env:
          AUTH_TOKEN: ${{ secrets.ACTIONS_PAT }}
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build
      
      - name: publish
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: ${{ github.event.repository.name }}
          command: github-release
          token: ${{ secrets.GITHUB_TOKEN }}
                   
