 # This is a basic workflow to help you get started with Actions

name: Publish package to Github

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release-please:
    runs-on: ubuntu-latest
    steps:
     - uses: google-github-actions/release-please-action@v3
       id: release
       with:
         release-type: node
         package-name: ${{ github.event.repository.name }}
         command: github-release
         token: ${{ secrets.GITHUB_TOKEN }}
         default-branch: main
         
     - name: log release status
       run: echo "release status - $release_status"
       env:
         release_status: ${{ steps.release.outputs.release_created }}
       
     - uses: actions/checkout@v2.3.4
       if: ${{ steps.release.outputs.release_created }}
     - uses: actions/setup-node@v2.5.1
       if: ${{ steps.release.outputs.release_created }}
       with:
         node-version: 14
     
     - name: Generate .npmrc for Private Repo
       if: ${{ steps.release.outputs.release_created }}
       uses: TwiggyBuffalo/create-npmrc@master
       with:
         org_name: fullfacing
       env:
         AUTH_TOKEN: ${{ secrets.ACTIONS_PAT }}
     # Runs a set of commands using the runners shell
     
     - name: Install dependencies
       if: ${{ steps.release.outputs.release_created }}
       run: npm ci
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Build
       if: ${{ steps.release.outputs.release_created }}
       run: npm run build

     - name: Publish
       if: ${{ steps.tag-release.outputs.releases_created }}
       env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         npm publish

  release-pr:
      runs-on: ubuntu-latest
      needs:
        - release-please
      strategy:
        fail-fast: false
      steps:
        - uses: google-github-actions/release-please-action@v3
          with:
              release-type: node
              package-name: ${{ github.event.repository.name }}
              command: github-release
              token: ${{ secrets.GITHUB_TOKEN }}
              default-branch: main
