 # This is a basic workflow to help you get started with Actions

name: Publish package to Github

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
    #Generates github release notes once release-pr is merged
    #Skips this job when this action runs the first time, needs the 
    #'release-pr' action to pass to make the pr.
    # once merged, this section generates the github release notes.
     - uses: google-github-actions/release-please-action@v3
       id: release
       with:
         release-type: node
         package-name: ${{ github.event.repository.name }}
         command: github-release
         token: ${{ secrets.GITHUB_TOKEN }}
         default-branch: main
       
     - uses: actions/checkout@v2.3.4
       if: ${{ steps.release.outputs.release_created }}
     - uses: actions/setup-node@v2.5.1
       if: ${{ steps.release.outputs.release_created }}
       with:
         node-version: 14
     
     - name: Generate .npmrc for Private Repo
       uses: TwiggyBuffalo/create-npmrc@master
       if: ${{ steps.release.outputs.release_created }}
       with:
         org_name: fullfacing
       env:
         AUTH_TOKEN: ${{ secrets.ACTIONS_PAT }}
     
     - name: Install dependencies
       if: ${{ steps.release.outputs.release_created }}
       run: npm ci
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Build
       if: ${{ steps.release.outputs.release_created }}
       run: npm run build

     - name: Publish
       if: ${{ steps.tag-release.outputs.releases_created }}
       env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: npm publish

#generates a release pr that needs to get merged.
#after this has run once, the second time this 
#runs (when the release pr gets merged) this doesn't 
#create an additional pr, on merge, 'github-release'
#will be pass and create the deployment and release notes
  release-pr:
      runs-on: ubuntu-latest
      needs:
        - github-release
      strategy:
        fail-fast: false
      steps:
        - uses: google-github-actions/release-please-action@v3
          with:
              release-type: node
              package-name: ${{ github.event.repository.name }}
              command: release-pr
              token: ${{ secrets.GITHUB_TOKEN }}
              default-branch: main
