name: Generate docs

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:

  - name: JSDoc Action
    uses: andstor/jsdoc-action@v1.2.1
    with:
    source_dir: ./src
    recurse: true
    output_dir: ./out

